Reimplement `mkdir -p` reporting where permissions break down
EESSI/software-layer pull request #228
Opened 2023-02-14 16:11 UTC by ocaisa

This will allow us to log where creating directory structures under `host_injections` is breaking down.

2023-02-14 16:17 UTC, ocaisa commented
Rate limits are an issue with out PRs, see https://github.com/EESSI/software-layer/actions/runs/4175759364/jobs/7231122992#step:4:32
(a proposed solution is described in https://github.com/EESSI/software-layer/issues/217)

2023-03-02 09:30 UTC, boegel requested changes

2023-03-02 09:30 UTC, boegel commented on scripts/utils.sh
> +    echo "Function requires a single (relative or absolute) path argument" >&2
`Function` -> `create_directory_structure`

```suggestion
    echo "ERROR: create_directory_structure requires a single (relative or absolute) path argument" >&2

2023-03-02 09:30 UTC, boegel commented on scripts/utils.sh
> +      echo "Directory ${directory_structure} exists but is not writeable" >&2
```suggestion
      echo "ERROR: Directory ${directory_structure} exists but is not writeable" >&2

2023-03-02 09:30 UTC, boegel commented on scripts/utils.sh
> +      return 1
Do we want different exit codes for different types of failures?

2023-03-02 09:30 UTC, boegel commented on scripts/utils.sh
> +    # (if this doesn't succeed we need to return the error code)
We're not returning the error code of the recursive call at all?

2023-03-02 09:30 UTC, boegel commented on scripts/utils.sh
> +    echo "Attempt to create ${full_structure} failed," \
```suggestion
    echo "ERROR: Attempt to create ${full_structure} failed," \

2023-03-02 09:30 UTC, boegel commented on scripts/utils.sh
> +      echo "'mkdir ${directory_structure}' failed for an unknown reason!" >&2
```suggestion
      echo "'ERROR: mkdir ${directory_structure}' failed for an unknown reason!" >&2

2023-03-02 09:31 UTC, boegel commented on scripts/utils.sh
> +# Reimplement 'mkdir -p' with reporting on where permissions break down
@ocaisa Maybe it makes sense to elaborate on the use case for this function a bit?
Why is `mkdir -p` not good enough, is it mainly to get better error reporting?

Can we add a reference to an issue on something here with more info?

2023-03-02 10:21 UTC, ocaisa commented
Urgh, I'm going to close this. `mkdir -p` actually does report the location where directory creation fails. A simple wrapper is enough to also report the full path it was trying to create, so I will just add that to #212 instead

2023-03-02 10:21 UTC, closed without merging