fix check for missing installations
EESSI/software-layer pull request #237
Opened 2023-03-07 14:34 UTC by trz42

fixes #236 

Added comments to explain the needed change.

Should we add a test for this?

2023-03-07 17:57 UTC, trz42 commented
Converted to a **draft** because it is only necessary if we use EB v4.7.0 or newer.

2023-03-08 10:50 UTC, trz42 commented
Changed script works for EB v4.5.1 (current latest EB version in EESSI pilot).

Added a test that captures a missing package.

The tests may fail if EB v4.7.0 or newer is used AND the format of the easystack file is not updated.

2023-04-11 07:09 UTC, boegel requested changes

2023-04-11 07:09 UTC, boegel commented on check_missing_installations.sh
> +# ` required modules missing:` and no other error happened)
@trz42 This comment looks like a TODO description, can be removed?

2023-04-11 14:05 UTC, boegel approved these changes
lgtm

2023-04-11 14:07 UTC, merged