{2023.06}[foss/2021a] Qt5 V5.15.2
EESSI/software-layer pull request #284
Opened 2023-06-27 06:48 UTC by TopRichard

2023-06-27 06:51 UTC, TopRichard commented
bot: build repo:eessi-2023.06-software arch:x86_64/generic

2023-06-27 11:57 UTC, TopRichard commented
bot: build repo:eessi-2023.06-software arch:x86_64/generic

2023-06-27 15:04 UTC, TopRichard commented
bot: build repo:eessi-2023.06-software arch:x86_64/generic

2023-06-28 09:00 UTC, TopRichard commented
Failure : build failed to determine installation prefix for binutils

2023-06-30 08:30 UTC, boegel commented
Sanity check failed:
```
== sanity checking...
== ... (took < 1 sec)
3:35:06  28 out of 29 easyconfigs done: libGLU/9.0.1-GCCcore-10.3.0 (OK), Mesa/2ERROR: Traceback (most recent call last):
  File "/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/EasyBuild/4.7.2/lib/python3.11/site-packages/easybuild/main.py", line 133, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/EasyBuild/4.7.2/lib/python3.11/site-packages/easybuild/framework/easyblock.py", line 4236, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/EasyBuild/4.7.2/lib/python3.11/site-packages/easybuild/framework/easyblock.py", line 4119, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/EasyBuild/4.7.2/lib/python3.11/site-packages/easybuild/framework/easyblock.py", line 3954, in run_step
    step_method(self)()
  File "/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/EasyBuild/4.7.2/lib/python3.11/site-packages/easybuild/easyblocks/q/qt.py", line 203, in sanity_check_step
    if LooseVersion(glibc_version) <= LooseVersion("2.16"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/pilot.eessi-hpc.org/versions/2023.06/compat/linux/x86_64/usr/lib/python3.11/site-packages/setuptools/_distutils/version.py", line 78, in __le__
    c = self._cmp(other)
        ^^^^^^^^^^^^^^^^
  File "/cvmfs/pilot.eessi-hpc.org/versions/2023.06/compat/linux/x86_64/usr/lib/python3.11/site-packages/setuptools/_distutils/version.py", line 351, in _cmp
    if self.version < other.version:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
```

So it seems like `glibc_version` is not a valid version for some reason...

2023-06-30 08:34 UTC, boegel commented
Indeed:
```
$ source /cvmfs/pilot.eessi-hpc.org/versions/2023.06/init/bash
$ module load EasyBuild/4.7.2
$ eb --show-system-info | grep glibc
  -> glibc version: UNKNOWN
```

Or more directly:

```
$ python -c 'from easybuild.tools.systemtools import get_glibc_version; print(get_glibc_version())'
UNKNOWN
```
```

2023-06-30 08:36 UTC, boegel commented
As a workaround, we can set `check_qtwebengine` to `False` through a hook before the `sanity_check_step` runs.

It doesn't affect the installation itself, only the sanity check part, where the `glibc` version is being checked to verify whether `libQtWebEngine` should be there, or not (it should be, since we have a very recent glibc).

2023-06-30 08:51 UTC, boegel commented
`glibc` version in EESSI compat layer will be detected correctly by EasyBuild once https://github.com/easybuilders/easybuild-framework/pull/4290 is merged

2023-06-30 09:48 UTC, TopRichard commented
@boegel Can we use the option:ignore-test-failure as it is the only test within the easyconfig file ?

2023-06-30 10:02 UTC, TopRichard commented
bot: build repo:eessi-2023.06-software arch:x86_64/generic

2023-07-01 09:54 UTC, boegel commented
> @boegel Can we use the option:ignore-test-failure as it is the only test within the easyconfig file ?

The `--ignore-test-failure` option is to ignore failing tests during the test step.
Here the problem is that the sanity check step is failing.

If you need help with implementing a hook to dance around this, let me know...

2023-07-04 12:46 UTC, TopRichard commented
bot: build repo:eessi-2023.06-software arch:x86_64/generic

2023-07-04 15:52 UTC, TopRichard commented
bot: build repo:eessi-2023.06-software arch:x86_64/generic

2023-07-05 05:00 UTC, TopRichard commented
bot: build repo:eessi-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi-2023.06-software arch:aarch64/generic
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_n1

2023-07-05 06:48 UTC, boegel requested changes

2023-07-05 06:48 UTC, boegel commented on eb_hooks.py
> +def Qt5_check_qtwebengine_disable(ec, eprefix):
@TopRichard Let's rename this to `parse_hook_Qt5_check_qtwebengine_disable`, and register it in `PARSE_HOOKS`, so we keep things consistent.

Done in https://github.com/TopRichard/bot-software-layer1/pull/13

2023-07-05 06:49 UTC, boegel requested changes

2023-07-05 06:49 UTC, boegel commented on eessi-2023.06-eb-4.7.2-2021a.yml
> +       options:
Let's add a comment to explain this:

```suggestion
       # add missing patch files for Qt5 5.15.2 to fix build problems with glibc 2.34,
       # see https://github.com/easybuilders/easybuild-easyconfigs/pull/18087
       options:    
```

2023-07-05 08:07 UTC, boegel commented on eessi-2023.06-eb-4.7.2-2021a.yml
> +# see https://github.com/easybuilders/easybuild-easyconfigs/pull/18087
@TopRichard Can we match the indent with `options:`, or does that cause trouble?

2023-07-05 08:35 UTC, boegel submitted a review, later dismissed
lgtm

2023-07-05 08:36 UTC, boegel commented
@TopRichard Let's trigger a rebuild for (only) `x86_64/generic` to make sure the refactored hooks are working, before we trigger a deploy?

2023-07-05 08:44 UTC, TopRichard commented
bot: build repo:eessi-2023.06-software arch:x86_64/generic

2023-07-05 17:22 UTC, boegel commented
All tarballs staged for ingestion

2023-07-05 20:29 UTC, boegel approved these changes

2023-07-05 20:32 UTC, merged