{2023.06}[foss/2021b] QuantumESPRESSO V6.8
EESSI/software-layer pull request #289
Opened 2023-06-28 10:55 UTC by TopRichard

2023-06-28 10:58 UTC, TopRichard commented
bot: build repo:eessi-2023.06-software arch:x86_64/generic

2023-06-29 09:23 UTC, boegel commented
We should get #283 deployed first, since there's trouble there with OpenBLAS...

2023-07-06 07:50 UTC, TopRichard commented
bot: build repo:eessi-2023.06-software arch:x86_64/generic

2023-07-06 10:44 UTC, TopRichard commented
bot: build repo:eessi-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi-2023.06-software arch:aarch64/generic
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_n1

2023-07-07 07:03 UTC, boegel requested changes

2023-07-07 07:03 UTC, boegel commented on eessi-2023.06-eb-4.7.2-2021b.yml
> +  - QuantumESPRESSO-6.8-foss-2021b.eb
@TopRichard It won't make a difference in terms of what gets built, but I would add a separate entry for `foss-2021b` itself, as a "checkpoint" in the easystack file:

```suggestion
  - foss-2021b.eb
  - QuantumESPRESSO-6.8-foss-2021b.eb

2023-07-07 07:23 UTC, boegel commented
all tarballs staged for ingestion

2023-07-07 09:15 UTC, TopRichard reviewed
Agreed

2023-07-07 14:06 UTC, boegel approved these changes

2023-07-07 14:06 UTC, merged