{2023.06}[foss/2021a] Arrow V6.0.0
EESSI/software-layer pull request #316
Opened 2023-08-10 07:11 UTC by TopRichard

2023-08-10 07:12 UTC, TopRichard commented
bot: build repo:eessi-2023.06-software arch:x86_64/generic

2023-09-05 12:45 UTC, TopRichard commented
bot: build repo:eessi-2023.06-software arch:x86_64/generic

2023-09-05 13:03 UTC, boegel commented
Previous attempt failed to build `pyarrow` with:

```
error: passing const std::vector<std::__cxx11::basic_string<char> > as this argument discards qualifiers [-fpermissive]
  164697 |   __pyx_cur_scope->__pyx_genexpr_arg_0 = __pyx_genexpr_arg_0;
         |                                          ^~~~~~~~~~~~~~~~~~~
  In file included from /cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/GCCcore/10.3.0/include/c++/10.3.0/vector:72,
                   from /tmp/eb-pvqsw2q9/eb-hvxwnqby/eb-q5cmbnqf/eb-s5tuxpc2/eb-__sjce5p/eb-qqeoear4/eb-33922t8v/eb-2xp5zz8z/eb-u1dcfqsb/eb-ty7vyg0z/pip-req-build-znsnpia7/build/temp.linux-x86_64-cpython-39/lib.cpp:1132:
  /cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/GCCcore/10.3.0/include/c++/10.3.0/bits/vector.tcc:198:5: note:   in call to std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >]
    198 |     vector<_Tp, _Alloc>::
        |     ^~~~~~~~~~~~~~~~~~~
  gmake[2]: *** [CMakeFiles/lib.dir/build.make:76: CMakeFiles/lib.dir/lib.cpp.o] Error 1
  gmake[1]: *** [CMakeFiles/Makefile2:446: CMakeFiles/lib.dir/all] Error 2
  gmake: *** [Makefile:91: all] Error 2
  error: command '/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/CMake/3.20.1-GCCcore-10.3.0/bin/cmake' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for pyarrow
Failed to build pyarrow
```

It looks like this could be fixed by https://github.com/easybuilders/easybuild-easyconfigs/pull/18348, so we need a `--from-pr` here?

2023-09-05 14:17 UTC, TopRichard commented
I don't have access to the logs, so as a first step, i tried rebuilding it, as it might be a failing to download or ...

2023-09-05 15:54 UTC, TopRichard commented
bot: build repo:eessi-2023.06-software arch:x86_64/generic

2023-09-05 20:11 UTC, TopRichard commented
The package is successfully built, yet the bot shows a failure.

2023-09-05 20:19 UTC, boegel commented
@TopRichard The bot reporting a failure is because it detected missing `git` installations, those were fixed in #326.

We now also manually removed the `ReFrame` installations so we can rebuild them in #311.

Once the latter is deployed & merged, we can resume here by rebuilding for all CPU targets, should work as expected...

2023-09-06 06:04 UTC, boegel commented
bot: build repo:eessi-2023.06-software

2023-09-06 07:53 UTC, boegel commented
Failed build for `RapidJSON-1.1.0-GCCcore-10.3.0.eb` on `aarch64/generic` due to:
```
cc1plus: error: switch -mcpu=generic conflicts with -march=armv8.2-a+crypto+fp16+rcpc+dotprod+ssbs switch [-Werror]
```

Similar issue with the `x86_64/generic` build actually, although the build there doesn't fail, but the build was done using `-march=x86-64 -mtune=generic -fno-math-errno -march=native` (and last option wins), so it's not actually a generic build at all.

Should be fixed with https://github.com/easybuilders/easybuild-easyconfigs/pull/18725

2023-09-06 07:58 UTC, boegel requested changes

2023-09-06 07:58 UTC, boegel commented on eessi-2023.06-eb-4.7.2-2021a.yml
> +         from-pr: 18348
```suggestion
  - RapidJSON-1.1.0-GCCcore-10.3.0.eb:
       # strip out hardcoded -march=native,
       # see https://github.com/easybuilders/easybuild-easyconfigs/pull/18725
       options:
         from-pr: 18725
  - Arrow-6.0.0-foss-2021a.eb:
       # fix installation of pyarrow Python bindings
       # see https://github.com/easybuilders/easybuild-easyconfigs/pull/18348
       options:
         from-pr: 18348

2023-09-06 08:15 UTC, boegel commented
bot: build repo:eessi-2023.06-software

2023-09-06 15:48 UTC, boegel approved these changes

2023-09-06 19:02 UTC, boegel commented
all staging PRs merged so deployment of this is happening very soon now

2023-09-06 20:18 UTC, merged