{2023.06}[foss/2021b] OpenFoam v2112
EESSI/software-layer pull request #330
Opened 2023-09-08 08:20 UTC by laraPPr

2023-09-08 08:21 UTC, laraPPr commented
bot: build repo:eessi-2023.06-software

2023-09-08 08:48 UTC, laraPPr commented
`7216`
```
== 2023-09-08 08:40:15,718 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Build of /cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/EasyBuild/4.8.0/easybuild/easyconfigs/m/MPFR/MPFR-4.1.0-GCCcore-11.2.0.eb failed (err: 'build failed (first 300 chars): cmd "mkdir -p /cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/MPFR/4.1.0-GCCcore-11.2.0/lib && cp -a src/.libs/libmpfr.so* /cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/MPFR/4.1.0-GCCcore-11.2.0/lib &&  make check  && rm -r /cvm') (at easybuild/main.py:174 in build_and_install_software)
```

2023-09-08 08:58 UTC, boegel commented
Hmm, looks like it's because a single test failed:

```
...
FAIL: tsprintf
...
============================================================================
Testsuite summary for MPFR 4.1.0
============================================================================
# TOTAL: 183
# PASS:  182
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
```

2023-09-08 09:04 UTC, boegel commented
@laraPPr Can you check if you find any clues upstream on this?

```
mpfr-4.1.0/tests/test-suite.log
======================================
   MPFR 4.1.0: tests/test-suite.log
======================================

# TOTAL: 183
# PASS:  182
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tsprintf
==============

Error in mpfr_vsprintf (s, "%0+ -'13.10Pd:", ...);
expected: "+01,234,567  :"
got:      "+0001,234,567:"
FAIL tsprintf (exit status: 1)
```

2023-09-08 09:32 UTC, laraPPr commented
I found this, [here](https://www.mpfr.org/mpfr-4.2.0/#fixed), but I don't know if it is relevant to us:

A test of the thousands separator in tsprintf.c is based on the output from the GNU C Library up to 2.36, which is [incorrect](https://sourceware.org/bugzilla/show_bug.cgi?id=23432). The output has changed in 2.37 (partly fixed), so that tsprintf fails with glibc 2.37. The [tsprintf-thousands patch](https://www.mpfr.org/mpfr-4.2.0/patch01) modifies the test to conform to POSIX and also avoid the buggy case in 2.36 and below. However, this new test, which was expected to succeed, triggers a serious bug in 2.37 ([bug 30068 / CVE-2023-25139](https://sourceware.org/bugzilla/show_bug.cgi?id=30068)). We did not modify the test again since this bug affects MPFR's mpfr_sprintf function, with a possible buffer overflow in particular cases. This bug has been [fixed in the 2.37 branch](https://sourceware.org/git/?p=glibc.git;a=commit;h=07b9521fc6369d000216b96562ff7c0ed32a16c4). In short, this patch is useful (and needed) for a fixed glibc 2.37 and some other libraries, depending on the current locales.
Corresponding changesets in the 4.2 branch: [4f03d40b5](https://gitlab.inria.fr/mpfr/mpfr/-/commit/4f03d40b5a5ceeb3126dc51c3511bdceef3bab19), [78ff7526d](https://gitlab.inria.fr/mpfr/mpfr/-/commit/78ff7526dea103f73acc98d9a9ffa7429050c0dd), [e66bb7121](https://gitlab.inria.fr/mpfr/mpfr/-/commit/e66bb71212b2789d783ccbc3b5b186247b972d5b).

2023-09-08 10:20 UTC, boegel commented
OK, excellent, so we should try and apply that patch to MPFR in EasyBuild, and then use `--from-pr` here.

2023-09-08 10:37 UTC, boegel commented
@laraPPr Let's see if https://github.com/easybuilders/easybuild-easyconfigs/pull/18746 fixes the MPFR test problem

2023-09-08 10:53 UTC, laraPPr commented
bot: build repo:eessi-2023.06-software arch:x86_64/generic

2023-09-08 11:13 UTC, laraPPr commented
bot: build repo:eessi-2023.06-software arch:x86_64/generic

2023-09-08 20:39 UTC, laraPPr commented
bot: build repo:eessi-2023.06-software arch:x86_64/intel/haswell 
bot: build repo:eessi-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi-2023.06-software arch:aarch64/generic
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_v1

2023-09-09 08:45 UTC, boegel commented
All 8 staging PRs merged, deployment under way...

2023-09-09 10:29 UTC, boegel requested changes

2023-09-09 10:29 UTC, boegel commented on eessi-2023.06-eb-4.8.0-2021b.yml
> +      #see https://github.com/easybuilders/easybuild-easyconfigs/pull/18746
```suggestion
      # use patch for MPFR 4.1.0 to fix failing tsprintf test with glibc >= 2.37,
      # see https://github.com/easybuilders/easybuild-easyconfigs/pull/18746

2023-09-09 11:05 UTC, boegel approved these changes

2023-09-09 11:05 UTC, merged