{2023.06}{GCCcore/12.3.0} BWA 0.7.17.20220923
EESSI/software-layer pull request #468
Opened 2024-02-08 13:38 UTC by hvelab

Re-taking Erica's [work](https://github.com/EESSI/software-layer/pull/429), adding latest BWA

2024-02-08 13:41 UTC, hvelab commented
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

2024-02-08 15:12 UTC, hvelab commented
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

2024-02-08 15:24 UTC, boegel commented
@hvelab It probably failed because `git_config` is used, see suggestions in https://github.com/easybuilders/easybuild-easyconfigs/pull/19820

2024-02-08 18:31 UTC, boegel commented
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

2024-02-08 18:50 UTC, boegel requested changes

2024-02-08 18:50 UTC, boegel commented on easystacks/software.eessi.io/2023.06/eessi-2023.06-eb-4.8.2-2023a.yml
> +  - BWA-0.7.17.20220923-GCCcore-12.3.0.eb:
```suggestion
  - BWA-0.7.17-20220923-GCCcore-12.3.0.eb:

2024-02-08 18:50 UTC, boegel commented
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

2024-02-08 19:03 UTC, boegel commented
Last attempt failed due to hitting GitHub rate limit:
```
== 2024-02-08 18:52:06,011 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Failed to get data for PR #19455 from easybuilders/easybuild-easyconfigs (HTTP Error 403: rate limit exceeded)
```

2024-02-08 19:52 UTC, boegel commented
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

2024-02-08 20:16 UTC, boegel commented
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

2024-02-08 21:31 UTC, boegel commented
all staging PRs merged

2024-02-09 12:38 UTC, bedroge approved these changes

2024-02-09 12:38 UTC, merged