Split setting of environment variables out from bash init script
EESSI/software-layer pull request #47
Opened 2020-11-26 10:43 UTC by ocaisa

2020-11-28 18:17 UTC, terjekv commented on init/bash
> +# (could switch to $(dirname "$(readlink -f "$BASH_SOURCE")") in that case)
`readlink -f` does not work on MacOS, so leaving that be might be just as well.

2020-11-28 18:17 UTC, terjekv commented
This looks pretty sane to me.  Should we aim to merge and test it until it's solid? Staying clear of `readlink -f ` due to the lack of MacOS support is a good idea.

2020-11-30 11:19 UTC, ocaisa commented on init/eessi_environment_variables
> +            EESSI_MODULEPATH=$EESSI_SOFTWARE_PATH/$EESSI_MODULE_SUBDIR
This is a way to support not just alternative MNS, but also domain-specific module trees (I can imagine combining this with domain easystack files)

2020-12-13 16:05 UTC, boegel requested changes

2020-12-13 16:05 UTC, boegel commented on init/eessi_environment_variables
> +  export EPREFIX=$EESSI_PREFIX/compat/$(uname -m)
@ocaisa This needs to be tweaked because there's an extra subdirectory `linux/` now, see https://github.com/ocaisa/software-layer/pull/1

2020-12-13 18:24 UTC, boegel approved these changes

2020-12-13 18:24 UTC, merged

2020-12-13 18:25 UTC, boegel commented
@bedroge Please "deploy":

```
$ ls /cvmfs/pilot.eessi-hpc.org/2020.12/init/
bash  eessi_environment_variables  eessi_software_subdir_for_host.py
```