{2023.06}[foss/2022b] waLBerla v6.1
EESSI/software-layer pull request #478
Opened 2024-02-16 19:41 UTC by Neves-P

Adds a minimal installation for `waLBerla` which does not contain the Python bindings or builds the benchmarks. The tutorials, however, are built and installed.

```
2 out of 43 required modules missing:

* Boost.MPI/1.81.0-gompi-2022b (Boost.MPI-1.81.0-gompi-2022b.eb)
* waLBerla/6.1-foss-2022b (waLBerla-6.1-foss-2022b.eb)
```

2024-02-17 08:42 UTC, boegel requested changes

2024-02-17 08:42 UTC, boegel commented on easystacks/software.eessi.io/2023.06/eessi-2023.06-eb-4.9.0-2022b.yml
> +  - waLBerla-6.1-foss-2022b.eb
```suggestion
  - waLBerla-6.1-foss-2022b.eb:

2024-02-17 08:42 UTC, boegel commented
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

2024-02-17 09:18 UTC, boegel commented
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

2024-02-17 12:22 UTC, Neves-P commented
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

2024-02-17 12:49 UTC, Neves-P commented
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

2024-02-18 21:34 UTC, boegel commented
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

2024-02-18 21:34 UTC, boegel approved these changes
lgtm

2024-02-19 08:11 UTC, merged