Add fix for permissions set on Lmod SitePackage
EESSI/software-layer pull request #538
Opened 2024-04-09 10:19 UTC by maxim-masterov

The current implementation of the `create_lmodsitepackage.py` script misses setting up the `read` permissions for the `other` UNIX group on the generated `SitePackage.lua` script:
```shell
$ ls -l /cvmfs/software.eessi.io/host_injections/2023.06/.lmod/SitePackage.lua
-rw-r----- 1 jenkins jenkins 2054 Apr  3 17:42 /cvmfs/software.eessi.io/host_injections/2023.06/.lmod/SitePackage.lua
```
As a result, users may experience errors like:
```shell
/cvmfs/[software.eessi.io/host_injections/2023.06/.lmod/SitePackage.lua](http://software.eessi.io/host_injections/2023.06/.lmod/SitePackage.lua): Permission denied
```
This PR fixes an issue by setting `664` permissions after the file is created.

2024-04-09 10:37 UTC, maxim-masterov commented
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

2024-04-10 14:07 UTC, ocaisa requested changes

2024-04-12 13:45 UTC, ocaisa approved these changes

2024-04-12 14:09 UTC, ocaisa commented
This has been deployed!

2024-04-12 14:10 UTC, merged