[WIP] update licenses
EESSI/software-layer pull request #675
Opened 2024-08-19 14:29 UTC by MartinsNadia

Open the new one to fix the origin branch

2024-10-15 09:09 UTC, ocaisa reviewed
Just had an initial look, perhaps you can add the current output of the script in a gist and link to this issue?

2024-10-15 09:09 UTC, ocaisa commented on licenses/check_licenses.yml
> +        uses: actions/setup-python@v4
Should use specific version here, see other workflows

2024-10-15 09:09 UTC, ocaisa commented on licenses/check_licenses.yml
> +        uses: peter-evans/create-pull-request@v5
Also needs specific commit

2024-10-15 09:09 UTC, ocaisa commented on licenses/check_licenses.yml
> +         branch: main #fork branch
This is not the correct branch for EESSI

2025-02-03 11:34 UTC, ocaisa requested changes

2025-02-03 11:34 UTC, ocaisa commented on .github/workflows/check_licenses.yml
> +          python update_licenses.py --source=github:easybuilders/easybuild EasyBuild
This could also help you decide where to look for licenses (since you have access to `source_urls`)

2025-02-27 18:02 UTC, hvelab commented
spare thoughts right now: 
- i kept the retrieval date because the original script did so, but i dont see much sense in keeping it, I would keep the license url instead 
- there are a lot of not found but i expect them to be less of them as right now some source_urls are still formatted with EB syntax but it my priority to fix it tomorrow
- need to fix the "needs manual action" part as its case sensitive right now with the "Other" licenses

2025-02-28 15:09 UTC, ocaisa commented on licenses/licenses.json
> +            "Other"
How did this end up with `Other`? I see it is GPL v2 at https://gitlab.gnome.org/Archive/atk

2025-02-28 15:18 UTC, ocaisa commented on licenses/licenses.json
> +            "Other"
License for this is https://github.com/apache/arrow/blob/main/LICENSE.txt ("Apache-2.0")

2025-02-28 15:31 UTC, ocaisa commented on licenses/licenses.json
> +        "License": "not found",
Apache 2.0 from https://github.com/bazelbuild/bazel/blob/master/LICENSE

2025-02-28 15:33 UTC, ocaisa commented on licenses/licenses.json
> +            "Other"
MIT from https://pypi.org/project/beautifulsoup4/

2025-02-28 15:35 UTC, ocaisa commented on licenses/licenses.json
> +        "License": "not found",
https://www.ffmpeg.org/legal.html

2025-03-03 09:50 UTC, hvelab commented on licenses/licenses.json
> +            "Other"
Agree, this is the plain response from the ecosyste.ms API: https://repos.ecosyste.ms/api/v1/repositories/lookup?url=https%3A%2F%2Fgithub.com%2Fredhotpenguin%2Fperl-Archive-Zip

Will work today on a "smarter" way to do this and to scrape other sources because there are much more not found licenses than found or other

2025-03-03 16:15 UTC, hvelab commented
Updates: 
- Fixed bug and now finds more licenses
- For the "Other" and "not found", does an scraping to go find the LICENSE file -> we need to find a way to retrieve the spdx from there 
- This needs to be improved for the packages with "Others" 
- For the totally "not found", shows source_urls and homepages, seems that most of them need to be sanitized or do the scraping from there, add more keywords

2025-03-11 20:21 UTC, hvelab commented
finished doing manual checks (while watching some random movie on the TV), we would just need permission for PGPLOT (https://sites.astro.caltech.edu/~tjp/pgplot/#copyright), and for CUDA im not sure if the propietary license allows us to redistribute it 
the scraper (aside from update_licenses.json) is good for an initial populate but to cover every single case is very difficult and required much more manual checks than expected, at least is done for now, for all software available in EESSI excluding extensions, which is my next focus, such as enforcing specifying the license from EB files

could try from a hook and if it fails then request the manual action? again, it's very difficult to scrape it from webpages and sometimes requires human interpretation

2025-06-27 13:05 UTC, laraPPr commented
@ocaisa should this be closed and moved to https://github.com/EESSI/software-layer-scripts?

2026-05-15 13:15 UTC, closed without merging

2026-05-15 13:15 UTC, ocaisa commented
Licences check is now in CI (but still being tweaked #1492)